In [1]:
print("ANKIt")

ANKIt


In [7]:
from numpy import random

x = random.randint(100)

print(x)

34


In [8]:
from numpy import random

x = random.rand()

print(x)

0.26538034270937105


In [12]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[40 74  8 45 38]


In [13]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[91 74 86 91 72]
 [41 31 49  0 41]
 [70 42 67 24 69]]


In [14]:
from numpy import random

x = random.rand(5)

print(x)

[0.27323883 0.07209234 0.68180612 0.53404191 0.84076888]


In [15]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.064203   0.55504035 0.2490029  0.2882896  0.03424371]
 [0.79466468 0.63940096 0.72367346 0.48065139 0.64935526]
 [0.35412972 0.26860221 0.40377683 0.23270943 0.36067306]]


In [21]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

7


In [22]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 3 3 3 3]
 [3 5 7 5 7]
 [7 5 5 5 7]]


In [23]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 3 7 5 7 5 7 7 7 5 7 7 7 5 7 3 7 7 7 7 7 3 3 5 7 7 5 7 7 5 7 7 3 3 7 7 5
 3 7 7 7 7 3 5 5 7 3 5 7 5 7 7 7 7 7 3 5 7 3 5 5 7 5 7 5 7 7 5 7 7 7 7 7 7
 7 7 5 7 7 3 5 5 7 7 7 7 7 7 7 7 7 5 7 7 5 7 7 7 7 7]


In [24]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 5 5 7 5]
 [5 5 7 5 3]
 [5 7 7 7 7]]
